### ISSUE TITLE
running on mac reads .DS_store and throws python error

### ISSUE THREAD

**Issue by gharp** [uwgraphics/VEP_TMScripts#1]
Here's the terminal output:

`EA-AMMIT:~ gharp$ cd /Users/gharp/Code/VisualizingEnglishPrint/VEP_TMScripts-master 
EA-AMMIT:VEP_TMScripts-master gharp$ python MalletModeler.py --corpus_path /Users/gharp/Code/VisualizingEnglishPrint/SerendipSlim-master/Data/Corpora/SPARC/ --output_path /Users/gharp/Code/VisualizingEnglishPrint/SerendipSlim-master/Models --model_name SPARC_mallet --num_topics 20 --mallet_stopwords
/Users/gharp/Code/VisualizingEnglishPrint/SerendipSlim-master/Models/SPARC_mallet already exists. Do you wish to overwrite it? (y/n) y
Reading corpus...
Reading text 1 of 595: .DS_Store...
Traceback (most recent call last):
  File "MalletModeler.py", line 576, in <module>
    main()
  File "MalletModeler.py", line 573, in main
    args.func(args)
  File "MalletModeler.py", line 64, in runSalTM
    textStr = inF.read()
  File "/Users/gharp/anaconda/lib/python2.7/codecs.py", line 686, in read
    return self.reader.read(size)
  File "/Users/gharp/anaconda/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 3131: invalid start byte
`

**Comment by simonlindgren** [comment]
Yes, It seems to read the .DS_Store. But if deleting .DS_Store, it runs as it should (the MalletModeler) but it writes a theta.csv with no topic numbers, so it can't be read into Serendip. The Gensim Modeler throws a `ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96`
